### ISSUE TITLE
Very very long processing on simple case

### ISSUE THREAD

**Issue by yvanblanchard** [Sanaxen/mesh2cad#3]
Hello,

I tried to apply segmentation on my OBJ mesh file (in order to generate IGES CAD file). The shape is simple, but it contains 60K triangles and almost 200K vertices.
The algorithm continues working for almost one hour (console logs), and I decided to stop processing before end.

I would like to know if it's normal or not ?

Here is image of the mesh:
![image](https://github.com/Sanaxen/mesh2cad/assets/63931618/4aa726dd-e393-4aed-a17e-cde1282797ed)

And the input OBJ file:
[subset.zip](https://github.com/Sanaxen/mesh2cad/files/15446963/subset.zip)

Thank you !

**Comment by Sanaxen** [comment]
Hello.
Segmentation failure.
This may be a bug, but the OBJ used for input is not a solid (closed shape), so it does not create a closed curve (loop).
Therefore, if I skip the segmentation, the process proceeds normally to the end.

[6519_Segment_1.zip](https://github.com/user-attachments/files/15750047/6519_Segment_1.zip)

mesh2cad_.batの
`..\bin\aut_segmentation.exe %tmp_id%.obj -lambda %2 -clusters %3
`
You can comment out this portion and add the following two lines
```
copy %tmp_id%.obj %tmp_id%_Segment_1.obj
copy %tmp_id%.obj %tmp_id%_Segment_1
```
It will look like this

```
: ..\bin\aut_segmentation.exe %tmp_id%.obj -lambda %2 -clusters %3
copy %tmp_id%.obj %tmp_id%_Segment_1.obj
copy %tmp_id%.obj %tmp_id%_Segment_1

```

**Comment by yvanblanchard** [comment]
Thank you @Sanaxen 
Does the segmentation process  works on watertight meshes only ?

**Comment by Sanaxen** [comment]
Yes, it does. I would have to take a closer look to be sure, but it could be a bug.

**Comment by yvanblanchard** [comment]
Since my mesh is not watertight , I think it’s Normal that the algorithm does not work. So u don’t understand why you have to investigate for a potential bug?

**Comment by Sanaxen** [comment]
Possible bug
 If the input is not a watertight mesh, the behavior is incorrect. Perhaps the segmentation resulted in the decomposition of the mesh into its component triangles.
